baseURL = "/"
languageCode = "en-gb"
publishDir = "docs"
theme = "harmony"
title = "Harmony Primary School"
[[menu.main]]
identifier = "parents"
name = "Parents"
weight = 4
[[menu.main]]
identifier = "curriculum"
name = "Curriculum"
weight = 3
[[menu.main]]
identifier = "school"
name = " Our School"
weight = 2
[params]
homepageImage = "/example-image.jpg"
homepageQuote = "An excellent education rooted in Islam"
