baseURL = "/"
languageCode = "en-gb"
publishDir = "docs"
theme = "harmony"
title = "Harmony Primary School"
[[menu.main]]
identifier = "contact"
name = "Contact us"
weight = 6
[[menu.main]]
identifier = "parents"
name = "Parents"
weight = 5
[[menu.main]]
identifier = "admissions"
name = "Admissions"
weight = 4
[[menu.main]]
identifier = "school"
name = " Our School"
weight = 2
[params]
homepageImage = "/example-image.jpg"
homepageQuote = "An excellent education rooted in Islam"
