baseURL = "/"
languageCode = "en-gb"
publishDir = "docs"
theme = "harmony"
title = "Harmony Primary School"
[params]
homepageImage = "/example-image.jpg"
homepageQuote = "An excellent education rooted in Islam"
