---
label: Default
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Forestry & Page Title
  description: This is the title that is shown in the user's tab, browser history
    and throughout Forestry.
pages:
- content/admissions/apply.md
- content/admissions/fees.md
- content/curriculum/assessment.md
- content/curriculum/home-learning.md
- content/curriculum/our-curriculum.md
- content/our-school/Vacancies/class-teacher-job-description.md
- content/our-school/Vacancies/education-support-assistant-job-description.md
- content/our-school/Vacancies/school-administrator-job-description.md
- content/our-school/headteachers-message.md
- content/our-school/our-staff.md
- content/our-school/our-vision.md
- content/our-school/vacancies.md
- content/parents/school-day.md
- content/parents/term-dates.md
- content/parents/uniform.md
