---
label: Default
hide_body: false
fields:
- name: content
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Content
  description: The content of the post
pages:
- content/our-school/careers.md
