---
label: Default
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Forestry-Only-Title
  description: This is the title that is used throughout Forestry.
pages:
- content/admissions/admissions.md
- content/admissions/apply.md
- content/admissions/fees.md
- content/our-school/headteachers-message.md
- content/our-school/our-staff.md
- content/our-school/vacancies.md
