---
label: Default
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Forestry-Only-Title
  description: This is the title that is used throughout Forestry.
pages:
- content/our-school/vacancies.md
- content/our-school/vision-statement.md
