---
label: Default
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Forestry-Only-Title
  description: This is the title that is used throughout Forestry.
pages:
- content/admissions/admissions-criteria.md
- content/admissions/apply.md
- content/admissions/fees.md
- content/curriculum/assessment.md
- content/curriculum/curriculum.md
- content/curriculum/home-learning.md
- content/our-school/headteachers-message.md
- content/our-school/our-staff.md
- content/our-school/vacancies.md
- content/parents/school-day.md
- content/parents/term-dates.md
- content/parents/uniform.md
